import { state } from "oly";
import { attach } from "oly-react";
import * as React from "react";
import { IDocs } from "../../shared/interfaces";

@attach
export class Footer extends React.Component<{}, {}> {
  @state("DOCS") private docs: IDocs;

  public render() {
    return (
      <div className="Footer">
        ~ oly v{this.docs.version} Generated by something the {new Date().toDateString()}. ~
      </div>
    );
  }
}
