import { attach } from "oly-react";
import * as React from "react";

@attach
export class Footer extends React.Component<{}, {}> {

  public render() {
    return (
      <div className="Footer">
        ~ Generated by something the {new Date().toDateString()}. ~
      </div>
    );
  }
}
